db_mysql: fix build against MariaDB 10.2
Fixes the following build error while building against MariaDB 10.2
library:

my_con.c: In function 'db_mysql_connect':
my_con.c:68:10: error: 'MYSQL {aka struct st_mysql}' has no member named
'reconnect'
ptr->con->reconnect = 0;
          ^~

In this new version of the library the reconnect field was moved to
another struct. Setting it through API seems to be a better approach.